### ISSUE TITLE
Infinite transmission notification

### ISSUE THREAD

**Issue by dmaterowski** [microsoft/opentelemetry-azure-monitor-python#73]
Hi,
When I set my logging to INFO level, I'm getting continuously a transmission success message, which in turn is transmitted, which.. once again logs a transmission success

```
2020-04-02 13:31:32,141 INFO Transmission succeeded: {"itemsReceived":1,"itemsAccepted":1,"errors":[]}.
2020-04-02 13:31:47,879 INFO Transmission succeeded: {"itemsReceived":1,"itemsAccepted":1,"errors":[]}.
2020-04-02 13:32:04,620 INFO Transmission succeeded: {"itemsReceived":1,"itemsAccepted":1,"errors":[]}.
```

There is a branch of code in https://github.com/microsoft/opentelemetry-azure-monitor-python/blob/master/azure_monitor/src/azure_monitor/export/__init__.py
```
if response.status_code == 200:
                logger.info("Transmission succeeded: %s.", text)
                return ExportResult.SUCCESS
```

**Comment by lzchen** [comment]
The `Transmission Succeeded` message is logged everytime a teleemtry envelope is sent successfully. Since  you are either using the trace or metrics exporter, it runs in a separate worker thread and exports every `export_interval` seconds. That is the reason you are seeing multiple messages in the logs. Secondly, the logs that you see would not be "transmitted" to Azure monitor anyways for 2 reasons:
1. Log exporter is not implemented yet
2. The Python `logger` is unique per name, the logger that is being used here belongs to `__init__.py` in the export folder. The only logs that would be exported would be from loggers that are in the user's applications.

**Comment by dmaterowski** [comment]
The transmission logs did end up in Azure monitor, however I can see how that's the application configuration issue.
The root logger was configured with an AzureLogHandler, causing this behaviour.
Thanks for clarifications!
