### ISSUE TITLE
how to add cloudRoleName and cloudInstanceName to python appinsights?

### ISSUE THREAD

**Issue by chetanku** [microsoft/opentelemetry-azure-monitor-python#95]
In .net and js libraries for appinsights you can add custom telemetry of cloudRolename and cloudInstancename, I don't see documentation around it for python.

for eg: https://www.davepaquette.com/archive/2020/02/05/setting-cloud-role-name-in-application-insights.aspx#:~:text=The%20application%20insights%20SDK%20sets,the%20app%20in%20App%20Service.

**Comment by lzchen** [comment]
Since this project is still in beta, we do not have production level documentation ready. You can refer to the [Microsoft official docs](https://docs.microsoft.com/en-us/azure/azure-monitor/app/api-filtering-sampling#opencensus-python-telemetry-processors) for OpenCensus Python SDK for Azure Monitor, which will be very similar to what OpenTelemetry would offer.
